---
apiVersion: apps/v1
kind: Deployment
metadata : 
   namespace: laravel
   name: laravel
   spec: 
    replicas: 3
    selector: 
      match_labels:
        app: mylaravelapp
      template: 
      metadata: 
        labels:
          app: = "my-laravel-app"
      spec :
        container:
        -  name: laravel-pod
           image: 3niola/webapp02:latest
           imagePULLPolicy: IfNotPresent
           ports: 
           - container_port:  80
        env:
          - name: PORT
            value: "80"
      
# }
# locals {
#   lb_name = split("-", split(".", kubernetes_service.laravel.status.0.load_balancer.0.ingress.0.hostname).0).0
# }
# # Read information about the load balancer using the AWS provider.
# data "aws_elb" "laravel" {
#   name = local.lb_name
# }

# output "load_balancer_name" {
#   value = local.lb_name
# }

# output "load_balancer_hostname" {
#   value = kubernetes_service.laravel.status.0.load_balancer.0.ingress.0.hostname
# }

# output "load_balancer_info" {
#   value = data.aws_elb.laravel
# }
# }
