apiVersion: v1
kind: Service
metadata:
  name: laravel
  labels:
    app: laravel
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: laravel
  type: LoadBalancer