---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: laravel
  namespace: laravel
  name: laravel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel
  template:
    metadata:
      labels:
        app: laravel
    spec:
      containers:
      - image: 3niola/webapp02:latest
        name: laravel

# }
# locals {
#   lb_name = split("-", split(".", kubernetes_service.laravel.status.0.load_balancer.0.ingress.0.hostname).0).0
# }
# # Read information about the load balancer using the AWS provider.
# data "aws_elb" "laravel" {
#   name = local.lb_name
# }

# output "load_balancer_name" {
#   value = local.lb_name
# }

# output "load_balancer_hostname" {
#   value = kubernetes_service.laravel.status.0.load_balancer.0.ingress.0.hostname
# }

# output "load_balancer_info" {
#   value = data.aws_elb.laravel
# }
# }
